#!/usr/bin/env bash
# a script to transfer local files to a server using scp

if [ "$#" -lt 4 ] then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

file_path="$1"
ip_server="$2"
username="$3"
identity_file="$4"

scp -o StrictHostKeyChecking=no -i "$identity_file" "$file_path" "$username"@"$ip_server":~/
