#!/usr/bin/env bash
# a script to install a web server on my server and implement a get request

apt-get update
apt-get -y install nginx

bash -c 'echo "server {
    listen 80;
    server_name _;
    location / {
        echo \"Hello World!\";
    }
}" > /etc/nginx/sites-available/default'

service nginx restart
