#!/usr/bin/env bash
# a bash script that handles different signals

handle_sigterm(){
	echo "I hate the kill command"
}

handle_sigint(){
	echo "Y U no love me?!"
	handle_quit
}

handle_quit(){
	rm /var/run/myscript.pid
	exit 1
}

echo "$$" > /var/run/myscript.pid

trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT
trap 'handle_quit' SIGQUIT
while true; do
	echo "To infinity and beyond"
	sleep 2
done
