#!/usr/bin/env bash
# a script that controls signal when received
handle_signal(){
	echo "I am invincible!!!"
}

trap 'handle_signal' SIGTERM
while true; do
	echo "To infinity and beyond"
	sleep 2
done
