#!/usr/bin/env bash
# a bash script  that displays the visitor IP along with the HTTP status code from the Apache log file.

file="apache-access.log"
if [ ! -e "$file" ]; then
	echo "Error: $file not found"
	exit
fi
awk '{ for (i=1; i<=NF; i++) { if ($i ~ /^[0-9][0-9][0-9]$/) { code=$i; break } } print $1, code }' "$file"
