#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
times=10
counter=0
while [ $counter -lt $times ]; do
	echo "Best School"
	if [ $counter = 8 ]; then
		echo "Hi"
	fi
	((counter++))
done
