#!/usr/bin/env bash
# a script that prints content according to the nth iteration
counter=1
while [ $counter -le 20 ]; do
	echo $counter
	case $counter in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
			echo $counter
			;;
	esac
	((counter++))
done
