#!/usr/bin/env bash
# a script that checks the existence of a file
filename="school"
if [ -e "$filename" ]; then
	echo "school file exists"
	if [ -s "$filename" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$filename" ]; then
		echo "school is a regular file"
	else
		:
	fi
else
	echo "school file does not exist"
fi
